"""Generate ``frontend/src/constants/enums.ts`` from ``app/common/enums/*.py``.

Run from ``backend/``:

    python scripts/sync_enums.py

This is the integration-quality contract: frontend reads enum *values* from the
generated file, and *labels* (Chinese display strings) from the hand-written
``frontend/src/constants/status-labels.ts``.

The generator imports every class re-exported by ``app.common.enums`` and emits:

    export type OrderStatus = "draft" | "pending_approval" | ...;
    export const OrderStatus = {
      Draft: "draft",
      PendingApproval: "pending_approval",
      ...
    } as const;
"""

from __future__ import annotations

import re
import sys
from enum import Enum
from pathlib import Path

# Make `app` importable when running from backend/
REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = REPO_ROOT / "backend"
sys.path.insert(0, str(BACKEND_ROOT))

from app.common import enums as enums_module  # noqa: E402

OUTPUT = REPO_ROOT / "frontend" / "src" / "constants" / "enums.ts"


def _snake_to_pascal(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_"))


def _emit(cls: type[Enum]) -> str:
    name = cls.__name__
    members = list(cls)
    if not members:
        return ""

    union = " | ".join(f'"{m.value}"' for m in members)
    obj_entries = ",\n  ".join(f'{_snake_to_pascal(m.name.lower())}: "{m.value}"' for m in members)
    values_list = ", ".join(f'"{m.value}"' for m in members)

    return (
        f"export type {name} = {union};\n"
        f"export const {name} = {{\n  {obj_entries},\n}} as const;\n"
        f"export const {name}Values: readonly {name}[] = [{values_list}] as const;\n"
    )


def _collect_enums() -> list[type[Enum]]:
    names: list[str] = list(enums_module.__all__)
    classes: list[type[Enum]] = []
    for n in names:
        obj = getattr(enums_module, n, None)
        if isinstance(obj, type) and issubclass(obj, Enum):
            classes.append(obj)
    return classes


def main() -> None:
    classes = _collect_enums()

    header = (
        "// AUTO-GENERATED by backend/scripts/sync_enums.py — DO NOT EDIT BY HAND.\n"
        "// Source: backend/app/common/enums/*.py\n"
        "// Run `python scripts/sync_enums.py` after changing any enum.\n"
        "//\n"
        "// Chinese display labels live in `./status-labels.ts`.\n\n"
    )

    body = "\n".join(_emit(cls) for cls in classes)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header + body, encoding="utf-8")

    # Pretty banner for the CLI
    enum_summary = ", ".join(cls.__name__ for cls in classes)
    sys.stdout.write(f"wrote {OUTPUT.relative_to(REPO_ROOT)} — {enum_summary}\n")


# Allow `python -m scripts.sync_enums` as well as direct invocation
if __name__ == "__main__":
    main()


# Sanity-check: the regex form of valid enum name (so file-level mistakes surface
# immediately during import even before main() runs).
_NAME_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")
for _n in enums_module.__all__:
    assert _NAME_RE.match(_n), f"enum class name not PascalCase: {_n}"
