// AUTO-GENERATED by backend/scripts/sync_enums.py — DO NOT EDIT BY HAND.
// Source: backend/app/common/enums/*.py
// Run `python scripts/sync_enums.py` after changing any enum.
//
// Chinese display labels live in `./status-labels.ts`.

export type AuditTargetType =
  | "order"
  | "sample"
  | "wip"
  | "machine"
  | "recipe"
  | "schedule"
  | "dispatch"
  | "experiment_run"
  | "report"
  | "issue"
  | "notification"
  | "user"
  | "role"
  | "lab"
  | "department"
  | "storage_location"
  | "system_setting"
  | "file";
export const AuditTargetType = {
  Order: "order",
  Sample: "sample",
  Wip: "wip",
  Machine: "machine",
  Recipe: "recipe",
  Schedule: "schedule",
  Dispatch: "dispatch",
  ExperimentRun: "experiment_run",
  Report: "report",
  Issue: "issue",
  Notification: "notification",
  User: "user",
  Role: "role",
  Lab: "lab",
  Department: "department",
  StorageLocation: "storage_location",
  SystemSetting: "system_setting",
  File: "file",
} as const;
export const AuditTargetTypeValues: readonly AuditTargetType[] = [
  "order",
  "sample",
  "wip",
  "machine",
  "recipe",
  "schedule",
  "dispatch",
  "experiment_run",
  "report",
  "issue",
  "notification",
  "user",
  "role",
  "lab",
  "department",
  "storage_location",
  "system_setting",
  "file",
] as const;

export type IssueAction = "approve" | "reject" | "close" | "escalate" | "assign" | "reopen";
export const IssueAction = {
  Approve: "approve",
  Reject: "reject",
  Close: "close",
  Escalate: "escalate",
  Assign: "assign",
  Reopen: "reopen",
} as const;
export const IssueActionValues: readonly IssueAction[] = [
  "approve",
  "reject",
  "close",
  "escalate",
  "assign",
  "reopen",
] as const;

export type IssueStatus = "open" | "assigned" | "escalated" | "acknowledged" | "closed";
export const IssueStatus = {
  Open: "open",
  Assigned: "assigned",
  Escalated: "escalated",
  Acknowledged: "acknowledged",
  Closed: "closed",
} as const;
export const IssueStatusValues: readonly IssueStatus[] = [
  "open",
  "assigned",
  "escalated",
  "acknowledged",
  "closed",
] as const;

export type IssueType = "abnormal" | "warning" | "termination_request";
export const IssueType = {
  Abnormal: "abnormal",
  Warning: "warning",
  TerminationRequest: "termination_request",
} as const;
export const IssueTypeValues: readonly IssueType[] = [
  "abnormal",
  "warning",
  "termination_request",
] as const;

export type MachineStatus = "idle" | "in_use" | "maintenance" | "faulty" | "disabled";
export const MachineStatus = {
  Idle: "idle",
  InUse: "in_use",
  Maintenance: "maintenance",
  Faulty: "faulty",
  Disabled: "disabled",
} as const;
export const MachineStatusValues: readonly MachineStatus[] = [
  "idle",
  "in_use",
  "maintenance",
  "faulty",
  "disabled",
] as const;

export type NotificationChannel = "in_app" | "email" | "phone";
export const NotificationChannel = {
  InApp: "in_app",
  Email: "email",
  Phone: "phone",
} as const;
export const NotificationChannelValues: readonly NotificationChannel[] = [
  "in_app",
  "email",
  "phone",
] as const;

export type NotificationStatus = "unread" | "read";
export const NotificationStatus = {
  Unread: "unread",
  Read: "read",
} as const;
export const NotificationStatusValues: readonly NotificationStatus[] = ["unread", "read"] as const;

export type OrderAction =
  | "submit"
  | "cancel"
  | "approve"
  | "return"
  | "reject"
  | "confirm_delivery"
  | "confirm_received"
  | "ready_for_pickup"
  | "close";
export const OrderAction = {
  Submit: "submit",
  Cancel: "cancel",
  Approve: "approve",
  Return: "return",
  Reject: "reject",
  ConfirmDelivery: "confirm_delivery",
  ConfirmReceived: "confirm_received",
  ReadyForPickup: "ready_for_pickup",
  Close: "close",
} as const;
export const OrderActionValues: readonly OrderAction[] = [
  "submit",
  "cancel",
  "approve",
  "return",
  "reject",
  "confirm_delivery",
  "confirm_received",
  "ready_for_pickup",
  "close",
] as const;

export type OrderStatus =
  | "draft"
  | "pending_approval"
  | "returned"
  | "rejected"
  | "approved"
  | "waiting_sample"
  | "received"
  | "split"
  | "scheduled"
  | "in_progress"
  | "waiting_result_confirm"
  | "completed"
  | "waiting_report_return"
  | "waiting_pickup"
  | "closed"
  | "cancelled"
  | "terminated";
export const OrderStatus = {
  Draft: "draft",
  PendingApproval: "pending_approval",
  Returned: "returned",
  Rejected: "rejected",
  Approved: "approved",
  WaitingSample: "waiting_sample",
  Received: "received",
  Split: "split",
  Scheduled: "scheduled",
  InProgress: "in_progress",
  WaitingResultConfirm: "waiting_result_confirm",
  Completed: "completed",
  WaitingReportReturn: "waiting_report_return",
  WaitingPickup: "waiting_pickup",
  Closed: "closed",
  Cancelled: "cancelled",
  Terminated: "terminated",
} as const;
export const OrderStatusValues: readonly OrderStatus[] = [
  "draft",
  "pending_approval",
  "returned",
  "rejected",
  "approved",
  "waiting_sample",
  "received",
  "split",
  "scheduled",
  "in_progress",
  "waiting_result_confirm",
  "completed",
  "waiting_report_return",
  "waiting_pickup",
  "closed",
  "cancelled",
  "terminated",
] as const;

export type ReportAction =
  | "submit_review"
  | "approve"
  | "reject"
  | "publish"
  | "return_to_user"
  | "create_revision";
export const ReportAction = {
  SubmitReview: "submit_review",
  Approve: "approve",
  Reject: "reject",
  Publish: "publish",
  ReturnToUser: "return_to_user",
  CreateRevision: "create_revision",
} as const;
export const ReportActionValues: readonly ReportAction[] = [
  "submit_review",
  "approve",
  "reject",
  "publish",
  "return_to_user",
  "create_revision",
] as const;

export type ReportStatus =
  | "draft"
  | "pending_review"
  | "confirmed"
  | "published"
  | "returned"
  | "revised";
export const ReportStatus = {
  Draft: "draft",
  PendingReview: "pending_review",
  Confirmed: "confirmed",
  Published: "published",
  Returned: "returned",
  Revised: "revised",
} as const;
export const ReportStatusValues: readonly ReportStatus[] = [
  "draft",
  "pending_review",
  "confirmed",
  "published",
  "returned",
  "revised",
] as const;

export type Severity = "low" | "medium" | "high" | "critical";
export const Severity = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Critical: "critical",
} as const;
export const SeverityValues: readonly Severity[] = ["low", "medium", "high", "critical"] as const;

export type StorageStatus = "in_lab" | "stored" | "pending_return" | "picked_up";
export const StorageStatus = {
  InLab: "in_lab",
  Stored: "stored",
  PendingReturn: "pending_return",
  PickedUp: "picked_up",
} as const;
export const StorageStatusValues: readonly StorageStatus[] = [
  "in_lab",
  "stored",
  "pending_return",
  "picked_up",
] as const;

export type UserStatus = "active" | "disabled";
export const UserStatus = {
  Active: "active",
  Disabled: "disabled",
} as const;
export const UserStatusValues: readonly UserStatus[] = ["active", "disabled"] as const;

export type WipAction =
  | "dispatch"
  | "schedule"
  | "load"
  | "unload"
  | "confirm"
  | "terminate"
  | "reopen";
export const WipAction = {
  Dispatch: "dispatch",
  Schedule: "schedule",
  Load: "load",
  Unload: "unload",
  Confirm: "confirm",
  Terminate: "terminate",
  Reopen: "reopen",
} as const;
export const WipActionValues: readonly WipAction[] = [
  "dispatch",
  "schedule",
  "load",
  "unload",
  "confirm",
  "terminate",
  "reopen",
] as const;

export type WipStatus =
  | "created"
  | "waiting_dispatch"
  | "in_schedule"
  | "waiting_load"
  | "running"
  | "unloaded"
  | "waiting_confirm"
  | "completed"
  | "terminated";
export const WipStatus = {
  Created: "created",
  WaitingDispatch: "waiting_dispatch",
  InSchedule: "in_schedule",
  WaitingLoad: "waiting_load",
  Running: "running",
  Unloaded: "unloaded",
  WaitingConfirm: "waiting_confirm",
  Completed: "completed",
  Terminated: "terminated",
} as const;
export const WipStatusValues: readonly WipStatus[] = [
  "created",
  "waiting_dispatch",
  "in_schedule",
  "waiting_load",
  "running",
  "unloaded",
  "waiting_confirm",
  "completed",
  "terminated",
] as const;
