"""0003 e add lab_id to issues

Revision ID: c78d6352388b
Revises: fea80b716b10
Create Date: 2026-05-25 19:12:39.203443

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c78d6352388b"
down_revision: str | Sequence[str] | None = "fea80b716b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issues", sa.Column("lab_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_issues_lab_id"), "issues", ["lab_id"], unique=False)
    op.create_foreign_key("issues_lab_id_fkey", "issues", "labs", ["lab_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("issues_lab_id_fkey", "issues", type_="foreignkey")
    op.drop_index(op.f("ix_issues_lab_id"), table_name="issues")
    op.drop_column("issues", "lab_id")
    # ### end Alembic commands ###
